name: 'UI tests'

on: push

permissions:
  pull_requests: read

jobs:
  cache-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Cache yarn dependencies and cypress
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-yarn-v3-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v3
      - name: Install dependencies if cache invalid
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: cache-dependencies
    steps:
      - uses: actions/checkout@v2
      - name: Get PR number
        id: pull_request
        run: echo "::set-output name=number::$(gh pr view --json number -q .number || echo "")"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Restore yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-yarn-v3-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v3
      - name: Build
        run: yarn build
      - uses: actions/github-script@v6
        with:
          script: console.log(github.event)
      - name: Pull Vercel configuration
        run: yarn vercel pull --yes --token ${{ secrets.vercel_token }}
      - name: Build Vercel bundle
        run: yarn vercel build
      - name: Deploy to Vercel
        run: yarn vercel deploy --prebuilt --token ${{ secrets.vercel_token }} > _vercel-deployment-url
      - name: Comment on PR with deployment URL
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const deploymentUrl = fs.readFileSync('_vercel-deployment-url', 'utf8');
            await github.rest.issues.createComment({
              issue_number: ${{ steps.pull_request.outputs.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Deployed to ${deploymentUrl}`,
            });

  interaction-and-and-accessibility:
    runs-on: ubuntu-latest
    needs: cache-dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Restore yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-yarn-v3-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v3
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: yarn build-storybook --quiet
      - name: Run Storybook tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && yarn test-storybook"

